# Generated by Django 5.2.4 on 2025-07-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
