# Generated by Django 5.2.4 on 2025-07-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_tag_tag_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
